name: test2

on:
  workflow_dispatch:
    inputs:
      iam-role-arn:
        description: 'IAM role ARN'
        required: true
      aws-region:
        description: 'AWS region'
        required: false
        default: 'ap-northeast-1'

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: aws
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ github.event.inputs.iam-role-arn }}
          aws-region: ${{ github.event.inputs.aws-region }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: ezqy/soci-action/setup@main
      - uses: ezqy/soci-action/aws-ecr-build-push@main
        with:
          tag: ${{ steps.aws.outputs.aws-account-id }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/soci-action:latest
          context: .

